### PR TITLE
Fix style of welcome module

### PR DESCRIPTION
**Pull request by molka**
Fix the RTL style of welcome module

### CODE REVIEW

**Comment by aleeks** [comment]
@molka 
Be careful, PR's module need to be done on `dev` branch.
Regards

**Comment by marionf** [comment]
I will test this when RTL will works on symfony pages

**Comment by marionf** [comment]
Hello @molka 

Some PR has been merged, can you please rebase ?

**Comment by marionf** [comment]
When I click on this button on the first step, nothing happens

capture d ecran_335

There are display problems and elements are superimposed 

capture d ecran_336

I don't have these issues on master branch, it seems better

**Pull request closed without merging**
