### PR TITLE
Fix preston position

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Preston on left was wrongly positionned
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#25527.
| How to test?  | Install the module and see if every steps are fine visually

### CODE REVIEW

**Comment by PierreRambaud** [comment]
The problem is fixed with this PR without changing the css: https://github.com/PrestaShop/welcome/pull/122 :thinking:

**Comment by NeOMakinG** [comment]
> The problem is fixed with this PR without changing the css: #122 🤔

If you compare the Update bourbon PR, you can see on line 55 on tooltips.scss that there is a mistake, I think you had cache or something like this

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
@hibatallahAouadni #122 is merged 😉

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is ok :heavy_check_mark: 
I checked with

- PS1769 (PHP7.1)
- 177x branch (PHP7.1)
- 178x branch (PHP7.2)
- develop branch (PHP7.4)

- I tried with desktop (chrome + firefox)
- I tried with mobile / tablet

https://drive.google.com/file/d/1R2fvyYY32fS-b6AgxO21gDDc2EvjkXj8/view?usp=sharing
Thanks!

**Comment by PierreRambaud** [comment]
Thank you @NeOMakinG

**Pull request merged**
