### PR TITLE
Fix wrong conditions on steps

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Some wrong conditions from eslints made the module unusable
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#21449.
| How to test?  | Try the welcome module

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I found this issue:

1. Reset the welcome module
2. Go to the Dashboard page (Onboarding popup is displayed)
3. Click on start (redirection to the Product page)
4. Click on Skip 
image
6. Go to the dashboard page
7. See error "onboarding-navbar" is not displayed anymore

It should be like
image

Same issue if we click Later button
https://drive.google.com/file/d/1XG9x2r-BRvaSPg_DHHm81DpJof8fQ-ac/view?usp=sharing

Thanks!

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@khouloudbelguith It seems to be OK. Could you test it ? (Thanks)

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG, @Progi1984,

I have a small differnce beween

- Branch 177x + PR welcome
- [PR](https://github.com/PrestaShop/PrestaShop/pull/21449) + PR welcome

Steps to reproduce the issue:
1. Reset the welcome module
2. Go to the Dashboard page (Onboarding popup is displayed)
3. Click on start (redirection to the Product page)
4. Click on Skip

- Branch 177x + PR welcome => OK
image
- [PR](https://github.com/PrestaShop/PrestaShop/pull/21449) + PR welcome => NOK
image

Is it related to the welcome module or the PR core?

Thanks to check!

**Comment by Progi1984** [comment]
@khouloudbelguith I think the PR is buggued because based on the another version (which have). I think you must test this PR as a module release independant from modules updates.

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG, @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1gsCKCTCKoV5rx86J0XQWPHFq1-eUTZ2C/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith & @NeOMakinG

**Pull request merged**
