### PR TITLE
Update bourbon and adapts BCs

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Bourbon is out of date, we wants to update it
| Type?         | improvement
| BC breaks?    | yes
| Deprecations? | no
| How to test?  | Try to build the module and everything should work as before

# BC

Bourbon is updated to 7.0.0, some mixins doesn't exist anymore such as transition, check his changelog!

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by florine2623** [comment]
Hello @NeOMakinG ,

I'm having visual issues with this PR. Here are some of the differences :

**_With PR :_**
Screenshot 2021-06-23 at 15 46 03
Screenshot 2021-06-23 at 15 46 56

**_Without PR :_**
Screenshot 2021-06-23 at 15 45 59
Screenshot 2021-06-23 at 15 46 45

Could you take a look please ?
Thanks!

**Comment by NeOMakinG** [comment]
good now @florine2623

**Comment by florine2623** [comment]
@NeOMakinG Thanks !

Some issues still remain

**2/6 - Step 2 - "Basic Setting is hidden"**
Screenshot 2021-06-24 at 10 25 40
Should be :
Screenshot 2021-06-24 at 10 25 26

**2/6 - Step 4 - Puffin in the middle :**
Screenshot 2021-06-24 at 10 22 54
Should be :
Screenshot 2021-06-24 at 10 23 03

**2/6 - Step 5 - Puffin in the middle :**
Screenshot 2021-06-24 at 10 29 09
Should be :
Screenshot 2021-06-24 at 10 29 14

It goes on like this for all the steps. Whether puffin is in the middle of the popup of the whole popup is pushed a little on a side.

Could you check again ? :)
Thanks!

**Comment by NeOMakinG** [comment]
Should be a mistake between px to rem, gonna look at it later

**Comment by NeOMakinG** [comment]
Ok fine @florine2623

**Comment by florine2623** [comment]
LGTM

Thanks a lot @NeOMakinG !

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
