### PR TITLE
Make welcome module compatible with older versions

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Following a discussion with @florine2623 , this module is no longer working with PrestaShop 1.7.8.x and 1.7.7.x. So to make it work again, I revert the change about strings indexes into integer. I also add a key ` name` to help people choice and add things if needed inside steps..
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Must work with 1.7.7.x, 1.7.8.x and develop branch.

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud,
> 
> I checked this PR with 177x & develop branch => NOK
> Before we have 6 steps.
> With this PR, we have only 5 steps.
> 
> 1. In step5 "Carriers page" => if you click next
>    image
> 2. The pop up is not displayed anymore
> 3. If you click continue => blocked
>    image
> 
> It should be
> image
> 
> Thanks!

There is no more 6 steps in this version.
Some pages will be deleted in the BO :thinking:

**Comment by PierreRambaud** [comment]
But I reproduce the issue with the last step

**Comment by PierreRambaud** [comment]
Should be better right now :p 
It redirects to the dashboard now

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

It is ok :heavy_check_mark: 
I checked with:

- PS1769
- 177x branch
- 178x branch
- develop branch

https://drive.google.com/file/d/1bVw5t3628i1yiNNVOVWL0NWVifrwj7_M/view?usp=sharing

Thanks!

**Review by matks — APPROVED** [review]

**Pull request merged**
