### PR TITLE
Release 6.0.9

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 6.0.9
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Comment by sallemiines** [comment]
Hello @Hlavtox 

Thanx for the PR ! 

I tried to check the PR , But when I install it,  I see that there is some conflicts

image


image



image


Could you please check it ! 
Waiting for your feedback ! 

Thank you

**Comment by SharakPL** [comment]
Merge conflicts are probably from #153 and #155 in _config.xml_. Both PRs change version number to 6.0.9.

**Review by SharakPL — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Comment by Hlavtox** [comment]
There should be no conflict now, I tested the merge on my fork and it went fine with no conflicts.

@sallemiines Can you retest it? We need the release ASAP because it's making troubles, please.

**Comment by sallemiines** [comment]
Hello @Hlavtox 

Thanx for the feedback , But unfortunately I re-test the Pr , and I find that the conflict still exist ! 

image

@kpodemski could you please check ? Github says there is no conflict, but when we try to install the PR, conflicts appears!

Thank you !

**Comment by Robin-Fischer-PS** [comment]
Hi @Hlavtox @kpodemski ,

Given the content of the release, I think we indeed can release it without functional tests, it can be merged :)

**Comment by Hlavtox** [comment]
Ping @kpodemski for merge 👍

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thanks @Hlavtox

**Pull request merged**
