### PR TITLE
Update design of last modal for PS 1.7.3.0

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
This PR fix the display of the last modal on PS 1.7.3.0.

Last modal, on PS 1.7.3.0:
capture d ecran de 2017-11-21 17-29-53

On PS 1.7.2.4, for backward compatibility:
capture d ecran de 2017-11-21 17-29-51

### CODE REVIEW

**Comment by eternoendless** [comment]
Shouldn't the minimum compatibility for the module be updated? Otherwise people on older PS versions might get a breaking update from the module.

**Comment by Quetzacoalt91** [comment]
I actually kept the backward compatibility, that's why there are 2 screenshots.

**Comment by eternoendless** [comment]
Ohhh nice 😄

**Comment by marionf** [comment]
I can't change the label, but it's ok for me :)

**Comment by eternoendless** [comment]
Thank you @Quetzacoalt91

**Pull request merged**
